// <auto-generated />
using Balistica.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Balistica.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Balistica.API.Model.Arma", b =>
                {
                    b.Property<int>("ArmaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Calibre");

                    b.Property<string>("Imagem");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.Property<string>("Tipo");

                    b.HasKey("ArmaId");

                    b.ToTable("Armas");
                });
#pragma warning restore 612, 618
        }
    }
}
